### ISSUE TITLE
[BUG] The problem with using the standard pattern "###,###.##"

### ISSUE THREAD

**Issue by neverlessy** [ItsWagPvP/EconomyPlus#57]
**Describe the bug**
Instead of the pattern, these symbols appear.

**To Reproduce**
1. Just use /balance

**Screenshots**
![image](https://user-images.githubusercontent.com/83380317/200587639-292a0dce-cb32-439e-9d07-7d14a993526b.png)

**Comment by jakepronger** [comment]
What language does this occur with?

**Comment by neverlessy** [comment]
> What language does this occur with?

Russian

**Comment by jakepronger** [comment]
I'll take a look. Thanks for the report.

**Comment by jakepronger** [comment]
Are you using any other plugins that hook into economy plus? Just to help me replicate this issue.

**Comment by Sandro642** [comment]
there is a problem with the Russian language ?

**Comment by neverlessy** [comment]
> Используете ли вы какие-либо другие плагины, подключаемые к economy plus? Просто чтобы помочь мне воспроизвести эту проблему.

no. Only this plugin

**Comment by jakepronger** [comment]
I can't replicate this issue. Can you please elaborate on how your getting this error? I changed my language to RU and did /balance.

**Comment by jakepronger** [comment]
This is likely an issue with your own custom pattern or something on your behalf. Since I failed to replicate this issue i'm not going to list it as an issue with the plugin however if this continues and you still need help please contact us by making a ticket on the discord and send your config.yml and RU.yml files.
